# Generated by Django 3.2.5 on 2021-07-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='image', upload_to='image/'),
        ),
    ]
